apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
        - name: {{ template "fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{default "Always" .Values.pullPolicy}}
          env:
          - name: POSTGRES_SERVER
            value: {{ .Values.postgresql.server | default (printf "%s-postgresql" ( .Release.Name )) | quote }}
          - name: POSTGRES_USERNAME
            value: {{ .Values.postgresql.username | default "postgres" | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.password | default "postgres" | quote }}
          - name: REDIS_HOST
            value: {{ .Values.redis.host | default (printf "%s-redis" ( .Release.Name )) | quote }}
