# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: harbor.demo.training.livew.io/livewyer-test/worker
  tag: 1.0.2

postgresql:
  postgresUser: postgres
  postgresPassword: postgres

redis:
  usePassword: false

replicaCount: 1