# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: v2.livew.io/training/worker
  tag: latest

postgresql:
  postgresUser: postgres
  postgresPassword: postgres

redis:
  usePassword: false

replicaCount: 1